# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DCLSUItest.ui'
#
# Created: Fri Nov 25 23:06:47 2022
#      by: PyQt4 UI code generator 4.9.5
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(1335, 954)
        MainWindow.setAutoFillBackground(True)
        MainWindow.setStyleSheet(_fromUtf8("MainWindow{border:2px rgb(255, 255, 255);}\n"
""))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(-15, 0, 1411, 931))
        self.label_4.setAutoFillBackground(False)
        self.label_4.setStyleSheet(_fromUtf8("border-image: url(:/background/background.png);"))
        self.label_4.setFrameShape(QtGui.QFrame.Box)
        self.label_4.setFrameShadow(QtGui.QFrame.Raised)
        self.label_4.setLineWidth(5)
        self.label_4.setText(_fromUtf8(""))
        self.label_4.setScaledContents(False)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.groupBox_2 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(200, 70, 281, 121))
        self.groupBox_2.setStyleSheet(_fromUtf8("background-color: rgb(235, 235, 235);"))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.layoutWidget = QtGui.QWidget(self.groupBox_2)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 18, 261, 94))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.gridLayout_4 = QtGui.QGridLayout(self.layoutWidget)
        self.gridLayout_4.setMargin(0)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.label_34 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_34.setFont(font)
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.gridLayout_4.addWidget(self.label_34, 0, 0, 1, 1)
        self.chart1_2 = QtGui.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.chart1_2.setFont(font)
        self.chart1_2.setObjectName(_fromUtf8("chart1_2"))
        self.gridLayout_4.addWidget(self.chart1_2, 0, 1, 1, 1)
        self.label_53 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_53.setFont(font)
        self.label_53.setObjectName(_fromUtf8("label_53"))
        self.gridLayout_4.addWidget(self.label_53, 0, 3, 1, 1)
        self.chart1_5 = QtGui.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.chart1_5.setFont(font)
        self.chart1_5.setObjectName(_fromUtf8("chart1_5"))
        self.gridLayout_4.addWidget(self.chart1_5, 0, 4, 1, 1)
        self.label_36 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_36.setFont(font)
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.gridLayout_4.addWidget(self.label_36, 1, 0, 1, 1)
        self.lineEdit_vm_pw1 = QtGui.QLineEdit(self.layoutWidget)
        self.lineEdit_vm_pw1.setStyleSheet(_fromUtf8("background-color: rgb(217, 217, 217);"))
        self.lineEdit_vm_pw1.setObjectName(_fromUtf8("lineEdit_vm_pw1"))
        self.gridLayout_4.addWidget(self.lineEdit_vm_pw1, 1, 1, 1, 1)
        self.label_35 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_35.setFont(font)
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.gridLayout_4.addWidget(self.label_35, 1, 2, 1, 1)
        self.label_56 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_56.setFont(font)
        self.label_56.setObjectName(_fromUtf8("label_56"))
        self.gridLayout_4.addWidget(self.label_56, 1, 3, 1, 1)
        self.lineEdit_vm_pw2 = QtGui.QLineEdit(self.layoutWidget)
        self.lineEdit_vm_pw2.setStyleSheet(_fromUtf8("background-color: rgb(217, 217, 217);"))
        self.lineEdit_vm_pw2.setObjectName(_fromUtf8("lineEdit_vm_pw2"))
        self.gridLayout_4.addWidget(self.lineEdit_vm_pw2, 1, 4, 1, 1)
        self.label_54 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_54.setFont(font)
        self.label_54.setObjectName(_fromUtf8("label_54"))
        self.gridLayout_4.addWidget(self.label_54, 1, 5, 1, 1)
        self.label_38 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_38.setFont(font)
        self.label_38.setObjectName(_fromUtf8("label_38"))
        self.gridLayout_4.addWidget(self.label_38, 2, 0, 1, 1)
        self.lineEdit_vm_pha1 = QtGui.QLineEdit(self.layoutWidget)
        self.lineEdit_vm_pha1.setStyleSheet(_fromUtf8("background-color: rgb(217, 217, 217);"))
        self.lineEdit_vm_pha1.setObjectName(_fromUtf8("lineEdit_vm_pha1"))
        self.gridLayout_4.addWidget(self.lineEdit_vm_pha1, 2, 1, 1, 1)
        self.label_37 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_37.setFont(font)
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.gridLayout_4.addWidget(self.label_37, 2, 2, 1, 1)
        self.label_52 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_52.setFont(font)
        self.label_52.setObjectName(_fromUtf8("label_52"))
        self.gridLayout_4.addWidget(self.label_52, 2, 3, 1, 1)
        self.lineEdit_vm_pha2 = QtGui.QLineEdit(self.layoutWidget)
        self.lineEdit_vm_pha2.setStyleSheet(_fromUtf8("background-color: rgb(217, 217, 217);"))
        self.lineEdit_vm_pha2.setObjectName(_fromUtf8("lineEdit_vm_pha2"))
        self.gridLayout_4.addWidget(self.lineEdit_vm_pha2, 2, 4, 1, 1)
        self.label_55 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_55.setFont(font)
        self.label_55.setObjectName(_fromUtf8("label_55"))
        self.gridLayout_4.addWidget(self.label_55, 2, 5, 1, 1)
        self.groupBox_4 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(850, 130, 281, 121))
        self.groupBox_4.setStyleSheet(_fromUtf8("background-color: rgb(235, 235, 235);"))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.layoutWidget1 = QtGui.QWidget(self.groupBox_4)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 18, 261, 94))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.gridLayout_5 = QtGui.QGridLayout(self.layoutWidget1)
        self.gridLayout_5.setMargin(0)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.label_40 = QtGui.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_40.setFont(font)
        self.label_40.setObjectName(_fromUtf8("label_40"))
        self.gridLayout_5.addWidget(self.label_40, 0, 0, 1, 1)
        self.chart1_3 = QtGui.QPushButton(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.chart1_3.setFont(font)
        self.chart1_3.setObjectName(_fromUtf8("chart1_3"))
        self.gridLayout_5.addWidget(self.chart1_3, 0, 1, 1, 1)
        self.label_59 = QtGui.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_59.setFont(font)
        self.label_59.setObjectName(_fromUtf8("label_59"))
        self.gridLayout_5.addWidget(self.label_59, 0, 3, 1, 1)
        self.chart1_6 = QtGui.QPushButton(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.chart1_6.setFont(font)
        self.chart1_6.setObjectName(_fromUtf8("chart1_6"))
        self.gridLayout_5.addWidget(self.chart1_6, 0, 4, 1, 1)
        self.label_43 = QtGui.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_43.setFont(font)
        self.label_43.setObjectName(_fromUtf8("label_43"))
        self.gridLayout_5.addWidget(self.label_43, 1, 0, 1, 1)
        self.lineEdit_ssa_pw1 = QtGui.QLineEdit(self.layoutWidget1)
        self.lineEdit_ssa_pw1.setStyleSheet(_fromUtf8("background-color: rgb(217, 217, 217);"))
        self.lineEdit_ssa_pw1.setObjectName(_fromUtf8("lineEdit_ssa_pw1"))
        self.gridLayout_5.addWidget(self.lineEdit_ssa_pw1, 1, 1, 1, 1)
        self.label_39 = QtGui.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_39.setFont(font)
        self.label_39.setObjectName(_fromUtf8("label_39"))
        self.gridLayout_5.addWidget(self.label_39, 1, 2, 1, 1)
        self.label_58 = QtGui.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_58.setFont(font)
        self.label_58.setObjectName(_fromUtf8("label_58"))
        self.gridLayout_5.addWidget(self.label_58, 1, 3, 1, 1)
        self.lineEdit_ssa_pw2 = QtGui.QLineEdit(self.layoutWidget1)
        self.lineEdit_ssa_pw2.setStyleSheet(_fromUtf8("background-color: rgb(217, 217, 217);"))
        self.lineEdit_ssa_pw2.setObjectName(_fromUtf8("lineEdit_ssa_pw2"))
        self.gridLayout_5.addWidget(self.lineEdit_ssa_pw2, 1, 4, 1, 1)
        self.label_61 = QtGui.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_61.setFont(font)
        self.label_61.setObjectName(_fromUtf8("label_61"))
        self.gridLayout_5.addWidget(self.label_61, 1, 5, 1, 1)
        self.label_41 = QtGui.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_41.setFont(font)
        self.label_41.setObjectName(_fromUtf8("label_41"))
        self.gridLayout_5.addWidget(self.label_41, 2, 0, 1, 1)
        self.lineEdit_ssa_pha1 = QtGui.QLineEdit(self.layoutWidget1)
        self.lineEdit_ssa_pha1.setStyleSheet(_fromUtf8("background-color: rgb(217, 217, 217);"))
        self.lineEdit_ssa_pha1.setObjectName(_fromUtf8("lineEdit_ssa_pha1"))
        self.gridLayout_5.addWidget(self.lineEdit_ssa_pha1, 2, 1, 1, 1)
        self.label_42 = QtGui.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_42.setFont(font)
        self.label_42.setObjectName(_fromUtf8("label_42"))
        self.gridLayout_5.addWidget(self.label_42, 2, 2, 1, 1)
        self.label_57 = QtGui.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_57.setFont(font)
        self.label_57.setObjectName(_fromUtf8("label_57"))
        self.gridLayout_5.addWidget(self.label_57, 2, 3, 1, 1)
        self.lineEdit_ssa_pha2 = QtGui.QLineEdit(self.layoutWidget1)
        self.lineEdit_ssa_pha2.setStyleSheet(_fromUtf8("background-color: rgb(217, 217, 217);"))
        self.lineEdit_ssa_pha2.setObjectName(_fromUtf8("lineEdit_ssa_pha2"))
        self.gridLayout_5.addWidget(self.lineEdit_ssa_pha2, 2, 4, 1, 1)
        self.label_60 = QtGui.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_60.setFont(font)
        self.label_60.setObjectName(_fromUtf8("label_60"))
        self.gridLayout_5.addWidget(self.label_60, 2, 5, 1, 1)
        self.groupBox_7 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_7.setGeometry(QtCore.QRect(870, 760, 281, 121))
        self.groupBox_7.setStyleSheet(_fromUtf8("background-color: rgb(235, 235, 235);"))
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.layoutWidget2 = QtGui.QWidget(self.groupBox_7)
        self.layoutWidget2.setGeometry(QtCore.QRect(10, 18, 261, 94))
        self.layoutWidget2.setObjectName(_fromUtf8("layoutWidget2"))
        self.gridLayout_9 = QtGui.QGridLayout(self.layoutWidget2)
        self.gridLayout_9.setMargin(0)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.label_75 = QtGui.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_75.setFont(font)
        self.label_75.setObjectName(_fromUtf8("label_75"))
        self.gridLayout_9.addWidget(self.label_75, 0, 0, 1, 1)
        self.chart1_11 = QtGui.QPushButton(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.chart1_11.setFont(font)
        self.chart1_11.setObjectName(_fromUtf8("chart1_11"))
        self.gridLayout_9.addWidget(self.chart1_11, 0, 1, 1, 1)
        self.label_79 = QtGui.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_79.setFont(font)
        self.label_79.setObjectName(_fromUtf8("label_79"))
        self.gridLayout_9.addWidget(self.label_79, 0, 3, 1, 1)
        self.chart1_10 = QtGui.QPushButton(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.chart1_10.setFont(font)
        self.chart1_10.setObjectName(_fromUtf8("chart1_10"))
        self.gridLayout_9.addWidget(self.chart1_10, 0, 4, 1, 1)
        self.label_83 = QtGui.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_83.setFont(font)
        self.label_83.setObjectName(_fromUtf8("label_83"))
        self.gridLayout_9.addWidget(self.label_83, 1, 0, 1, 1)
        self.lineEdit_load_pw1 = QtGui.QLineEdit(self.layoutWidget2)
        self.lineEdit_load_pw1.setStyleSheet(_fromUtf8("background-color: rgb(217, 217, 217);"))
        self.lineEdit_load_pw1.setObjectName(_fromUtf8("lineEdit_load_pw1"))
        self.gridLayout_9.addWidget(self.lineEdit_load_pw1, 1, 1, 1, 1)
        self.label_74 = QtGui.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_74.setFont(font)
        self.label_74.setObjectName(_fromUtf8("label_74"))
        self.gridLayout_9.addWidget(self.label_74, 1, 2, 1, 1)
        self.label_78 = QtGui.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_78.setFont(font)
        self.label_78.setObjectName(_fromUtf8("label_78"))
        self.gridLayout_9.addWidget(self.label_78, 1, 3, 1, 1)
        self.lineEdit_load_pw2 = QtGui.QLineEdit(self.layoutWidget2)
        self.lineEdit_load_pw2.setStyleSheet(_fromUtf8("background-color: rgb(217, 217, 217);"))
        self.lineEdit_load_pw2.setObjectName(_fromUtf8("lineEdit_load_pw2"))
        self.gridLayout_9.addWidget(self.lineEdit_load_pw2, 1, 4, 1, 1)
        self.label_81 = QtGui.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_81.setFont(font)
        self.label_81.setObjectName(_fromUtf8("label_81"))
        self.gridLayout_9.addWidget(self.label_81, 1, 5, 1, 1)
        self.label_77 = QtGui.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_77.setFont(font)
        self.label_77.setObjectName(_fromUtf8("label_77"))
        self.gridLayout_9.addWidget(self.label_77, 2, 0, 1, 1)
        self.lineEdit_load_pha1 = QtGui.QLineEdit(self.layoutWidget2)
        self.lineEdit_load_pha1.setStyleSheet(_fromUtf8("background-color: rgb(217, 217, 217);"))
        self.lineEdit_load_pha1.setObjectName(_fromUtf8("lineEdit_load_pha1"))
        self.gridLayout_9.addWidget(self.lineEdit_load_pha1, 2, 1, 1, 1)
        self.label_82 = QtGui.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_82.setFont(font)
        self.label_82.setObjectName(_fromUtf8("label_82"))
        self.gridLayout_9.addWidget(self.label_82, 2, 2, 1, 1)
        self.label_76 = QtGui.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_76.setFont(font)
        self.label_76.setObjectName(_fromUtf8("label_76"))
        self.gridLayout_9.addWidget(self.label_76, 2, 3, 1, 1)
        self.lineEdit_load_pha2 = QtGui.QLineEdit(self.layoutWidget2)
        self.lineEdit_load_pha2.setStyleSheet(_fromUtf8("background-color: rgb(217, 217, 217);"))
        self.lineEdit_load_pha2.setObjectName(_fromUtf8("lineEdit_load_pha2"))
        self.gridLayout_9.addWidget(self.lineEdit_load_pha2, 2, 4, 1, 1)
        self.label_80 = QtGui.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_80.setFont(font)
        self.label_80.setObjectName(_fromUtf8("label_80"))
        self.gridLayout_9.addWidget(self.label_80, 2, 5, 1, 1)
        self.groupBox_8 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_8.setGeometry(QtCore.QRect(460, 380, 281, 121))
        self.groupBox_8.setStyleSheet(_fromUtf8("background-color: rgb(235, 235, 235);"))
        self.groupBox_8.setObjectName(_fromUtf8("groupBox_8"))
        self.layoutWidget3 = QtGui.QWidget(self.groupBox_8)
        self.layoutWidget3.setGeometry(QtCore.QRect(10, 18, 261, 94))
        self.layoutWidget3.setObjectName(_fromUtf8("layoutWidget3"))
        self.gridLayout_7 = QtGui.QGridLayout(self.layoutWidget3)
        self.gridLayout_7.setMargin(0)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.label_85 = QtGui.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_85.setFont(font)
        self.label_85.setObjectName(_fromUtf8("label_85"))
        self.gridLayout_7.addWidget(self.label_85, 0, 0, 1, 1)
        self.chart1_13 = QtGui.QPushButton(self.layoutWidget3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.chart1_13.setFont(font)
        self.chart1_13.setObjectName(_fromUtf8("chart1_13"))
        self.gridLayout_7.addWidget(self.chart1_13, 0, 1, 1, 1)
        self.label_89 = QtGui.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_89.setFont(font)
        self.label_89.setObjectName(_fromUtf8("label_89"))
        self.gridLayout_7.addWidget(self.label_89, 0, 3, 1, 1)
        self.chart1_12 = QtGui.QPushButton(self.layoutWidget3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.chart1_12.setFont(font)
        self.chart1_12.setObjectName(_fromUtf8("chart1_12"))
        self.gridLayout_7.addWidget(self.chart1_12, 0, 4, 1, 1)
        self.label_93 = QtGui.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_93.setFont(font)
        self.label_93.setObjectName(_fromUtf8("label_93"))
        self.gridLayout_7.addWidget(self.label_93, 1, 0, 1, 1)
        self.lineEdit_kly_pw1 = QtGui.QLineEdit(self.layoutWidget3)
        self.lineEdit_kly_pw1.setStyleSheet(_fromUtf8("background-color: rgb(217, 217, 217);"))
        self.lineEdit_kly_pw1.setObjectName(_fromUtf8("lineEdit_kly_pw1"))
        self.gridLayout_7.addWidget(self.lineEdit_kly_pw1, 1, 1, 1, 1)
        self.label_84 = QtGui.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_84.setFont(font)
        self.label_84.setObjectName(_fromUtf8("label_84"))
        self.gridLayout_7.addWidget(self.label_84, 1, 2, 1, 1)
        self.label_88 = QtGui.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_88.setFont(font)
        self.label_88.setObjectName(_fromUtf8("label_88"))
        self.gridLayout_7.addWidget(self.label_88, 1, 3, 1, 1)
        self.lineEdit_kly_pw2 = QtGui.QLineEdit(self.layoutWidget3)
        self.lineEdit_kly_pw2.setStyleSheet(_fromUtf8("background-color: rgb(217, 217, 217);"))
        self.lineEdit_kly_pw2.setObjectName(_fromUtf8("lineEdit_kly_pw2"))
        self.gridLayout_7.addWidget(self.lineEdit_kly_pw2, 1, 4, 1, 1)
        self.label_91 = QtGui.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_91.setFont(font)
        self.label_91.setObjectName(_fromUtf8("label_91"))
        self.gridLayout_7.addWidget(self.label_91, 1, 5, 1, 1)
        self.label_87 = QtGui.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_87.setFont(font)
        self.label_87.setObjectName(_fromUtf8("label_87"))
        self.gridLayout_7.addWidget(self.label_87, 2, 0, 1, 1)
        self.lineEdit_kly_pha1 = QtGui.QLineEdit(self.layoutWidget3)
        self.lineEdit_kly_pha1.setStyleSheet(_fromUtf8("background-color: rgb(217, 217, 217);"))
        self.lineEdit_kly_pha1.setObjectName(_fromUtf8("lineEdit_kly_pha1"))
        self.gridLayout_7.addWidget(self.lineEdit_kly_pha1, 2, 1, 1, 1)
        self.label_92 = QtGui.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_92.setFont(font)
        self.label_92.setObjectName(_fromUtf8("label_92"))
        self.gridLayout_7.addWidget(self.label_92, 2, 2, 1, 1)
        self.label_86 = QtGui.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_86.setFont(font)
        self.label_86.setObjectName(_fromUtf8("label_86"))
        self.gridLayout_7.addWidget(self.label_86, 2, 3, 1, 1)
        self.lineEdit_kly_pha2 = QtGui.QLineEdit(self.layoutWidget3)
        self.lineEdit_kly_pha2.setStyleSheet(_fromUtf8("background-color: rgb(217, 217, 217);"))
        self.lineEdit_kly_pha2.setObjectName(_fromUtf8("lineEdit_kly_pha2"))
        self.gridLayout_7.addWidget(self.lineEdit_kly_pha2, 2, 4, 1, 1)
        self.label_90 = QtGui.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_90.setFont(font)
        self.label_90.setObjectName(_fromUtf8("label_90"))
        self.gridLayout_7.addWidget(self.label_90, 2, 5, 1, 1)
        self.groupBox_6 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_6.setGeometry(QtCore.QRect(840, 580, 281, 121))
        self.groupBox_6.setStyleSheet(_fromUtf8("background-color: rgb(235, 235, 235);"))
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.layoutWidget4 = QtGui.QWidget(self.groupBox_6)
        self.layoutWidget4.setGeometry(QtCore.QRect(10, 18, 261, 91))
        self.layoutWidget4.setObjectName(_fromUtf8("layoutWidget4"))
        self.gridLayout_8 = QtGui.QGridLayout(self.layoutWidget4)
        self.gridLayout_8.setMargin(0)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.label_67 = QtGui.QLabel(self.layoutWidget4)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_67.setFont(font)
        self.label_67.setObjectName(_fromUtf8("label_67"))
        self.gridLayout_8.addWidget(self.label_67, 2, 3, 1, 1)
        self.label_73 = QtGui.QLabel(self.layoutWidget4)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_73.setFont(font)
        self.label_73.setObjectName(_fromUtf8("label_73"))
        self.gridLayout_8.addWidget(self.label_73, 1, 0, 1, 1)
        self.label_50 = QtGui.QLabel(self.layoutWidget4)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_50.setFont(font)
        self.label_50.setObjectName(_fromUtf8("label_50"))
        self.gridLayout_8.addWidget(self.label_50, 0, 0, 1, 1)
        self.label_69 = QtGui.QLabel(self.layoutWidget4)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_69.setFont(font)
        self.label_69.setObjectName(_fromUtf8("label_69"))
        self.gridLayout_8.addWidget(self.label_69, 0, 3, 1, 1)
        self.label_70 = QtGui.QLabel(self.layoutWidget4)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_70.setFont(font)
        self.label_70.setObjectName(_fromUtf8("label_70"))
        self.gridLayout_8.addWidget(self.label_70, 2, 5, 1, 1)
        self.label_68 = QtGui.QLabel(self.layoutWidget4)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_68.setFont(font)
        self.label_68.setObjectName(_fromUtf8("label_68"))
        self.gridLayout_8.addWidget(self.label_68, 1, 3, 1, 1)
        self.label_49 = QtGui.QLabel(self.layoutWidget4)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_49.setFont(font)
        self.label_49.setObjectName(_fromUtf8("label_49"))
        self.gridLayout_8.addWidget(self.label_49, 1, 2, 1, 1)
        self.lineEdit_defl_pha1 = QtGui.QLineEdit(self.layoutWidget4)
        self.lineEdit_defl_pha1.setStyleSheet(_fromUtf8("background-color: rgb(217, 217, 217);"))
        self.lineEdit_defl_pha1.setObjectName(_fromUtf8("lineEdit_defl_pha1"))
        self.gridLayout_8.addWidget(self.lineEdit_defl_pha1, 2, 1, 1, 1)
        self.lineEdit_defl_pha2 = QtGui.QLineEdit(self.layoutWidget4)
        self.lineEdit_defl_pha2.setStyleSheet(_fromUtf8("background-color: rgb(217, 217, 217);"))
        self.lineEdit_defl_pha2.setObjectName(_fromUtf8("lineEdit_defl_pha2"))
        self.gridLayout_8.addWidget(self.lineEdit_defl_pha2, 2, 4, 1, 1)
        self.lineEdit_defl_pw2 = QtGui.QLineEdit(self.layoutWidget4)
        self.lineEdit_defl_pw2.setStyleSheet(_fromUtf8("background-color: rgb(217, 217, 217);"))
        self.lineEdit_defl_pw2.setObjectName(_fromUtf8("lineEdit_defl_pw2"))
        self.gridLayout_8.addWidget(self.lineEdit_defl_pw2, 1, 4, 1, 1)
        self.label_71 = QtGui.QLabel(self.layoutWidget4)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_71.setFont(font)
        self.label_71.setObjectName(_fromUtf8("label_71"))
        self.gridLayout_8.addWidget(self.label_71, 1, 5, 1, 1)
        self.chart1_9 = QtGui.QPushButton(self.layoutWidget4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.chart1_9.setFont(font)
        self.chart1_9.setObjectName(_fromUtf8("chart1_9"))
        self.gridLayout_8.addWidget(self.chart1_9, 0, 1, 1, 1)
        self.lineEdit_defl_pw1 = QtGui.QLineEdit(self.layoutWidget4)
        self.lineEdit_defl_pw1.setStyleSheet(_fromUtf8("background-color: rgb(217, 217, 217);"))
        self.lineEdit_defl_pw1.setObjectName(_fromUtf8("lineEdit_defl_pw1"))
        self.gridLayout_8.addWidget(self.lineEdit_defl_pw1, 1, 1, 1, 1)
        self.label_72 = QtGui.QLabel(self.layoutWidget4)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_72.setFont(font)
        self.label_72.setObjectName(_fromUtf8("label_72"))
        self.gridLayout_8.addWidget(self.label_72, 2, 2, 1, 1)
        self.chart1_8 = QtGui.QPushButton(self.layoutWidget4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.chart1_8.setFont(font)
        self.chart1_8.setObjectName(_fromUtf8("chart1_8"))
        self.gridLayout_8.addWidget(self.chart1_8, 0, 4, 1, 1)
        self.label_51 = QtGui.QLabel(self.layoutWidget4)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_51.setFont(font)
        self.label_51.setObjectName(_fromUtf8("label_51"))
        self.gridLayout_8.addWidget(self.label_51, 2, 0, 1, 1)
        self.groupBox_5 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_5.setGeometry(QtCore.QRect(1100, 380, 161, 121))
        self.groupBox_5.setStyleSheet(_fromUtf8("background-color: rgb(235, 235, 235);"))
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.layoutWidget5 = QtGui.QWidget(self.groupBox_5)
        self.layoutWidget5.setGeometry(QtCore.QRect(10, 18, 141, 96))
        self.layoutWidget5.setObjectName(_fromUtf8("layoutWidget5"))
        self.gridLayout_6 = QtGui.QGridLayout(self.layoutWidget5)
        self.gridLayout_6.setMargin(0)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.label_62 = QtGui.QLabel(self.layoutWidget5)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_62.setFont(font)
        self.label_62.setObjectName(_fromUtf8("label_62"))
        self.gridLayout_6.addWidget(self.label_62, 0, 0, 1, 1)
        self.chart1_4 = QtGui.QPushButton(self.layoutWidget5)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.chart1_4.setFont(font)
        self.chart1_4.setObjectName(_fromUtf8("chart1_4"))
        self.gridLayout_6.addWidget(self.chart1_4, 0, 1, 1, 1)
        self.lineEdit_refl_pw = QtGui.QLineEdit(self.layoutWidget5)
        self.lineEdit_refl_pw.setStyleSheet(_fromUtf8("background-color: rgb(217, 217, 217);"))
        self.lineEdit_refl_pw.setObjectName(_fromUtf8("lineEdit_refl_pw"))
        self.gridLayout_6.addWidget(self.lineEdit_refl_pw, 1, 1, 1, 1)
        self.label_47 = QtGui.QLabel(self.layoutWidget5)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_47.setFont(font)
        self.label_47.setObjectName(_fromUtf8("label_47"))
        self.gridLayout_6.addWidget(self.label_47, 1, 2, 1, 1)
        self.label_46 = QtGui.QLabel(self.layoutWidget5)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_46.setFont(font)
        self.label_46.setObjectName(_fromUtf8("label_46"))
        self.gridLayout_6.addWidget(self.label_46, 2, 0, 1, 1)
        self.chart1_14 = QtGui.QPushButton(self.layoutWidget5)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.chart1_14.setFont(font)
        self.chart1_14.setObjectName(_fromUtf8("chart1_14"))
        self.gridLayout_6.addWidget(self.chart1_14, 2, 1, 1, 1)
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(50, 578, 281, 321))
        self.groupBox.setStyleSheet(_fromUtf8("background-color: rgb(235, 235, 235);"))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.layoutWidget6 = QtGui.QWidget(self.groupBox)
        self.layoutWidget6.setGeometry(QtCore.QRect(20, 128, 241, 179))
        self.layoutWidget6.setObjectName(_fromUtf8("layoutWidget6"))
        self.gridLayout = QtGui.QGridLayout(self.layoutWidget6)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_10 = QtGui.QLabel(self.layoutWidget6)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout.addWidget(self.label_10, 0, 1, 1, 1)
        self.label_13 = QtGui.QLabel(self.layoutWidget6)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_13.setFont(font)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout.addWidget(self.label_13, 0, 2, 1, 1)
        self.label_8 = QtGui.QLabel(self.layoutWidget6)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout.addWidget(self.label_8, 1, 0, 1, 1)
        self.lineEdit_amp1set = QtGui.QLineEdit(self.layoutWidget6)
        self.lineEdit_amp1set.setObjectName(_fromUtf8("lineEdit_amp1set"))
        self.gridLayout.addWidget(self.lineEdit_amp1set, 1, 1, 1, 1)
        self.lineEdit_amp1act = QtGui.QLineEdit(self.layoutWidget6)
        self.lineEdit_amp1act.setStyleSheet(_fromUtf8("background-color: rgb(217, 217, 217);"))
        self.lineEdit_amp1act.setObjectName(_fromUtf8("lineEdit_amp1act"))
        self.gridLayout.addWidget(self.lineEdit_amp1act, 1, 2, 1, 1)
        self.label_9 = QtGui.QLabel(self.layoutWidget6)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout.addWidget(self.label_9, 2, 0, 1, 1)
        self.lineEdit_pha1set = QtGui.QLineEdit(self.layoutWidget6)
        self.lineEdit_pha1set.setObjectName(_fromUtf8("lineEdit_pha1set"))
        self.gridLayout.addWidget(self.lineEdit_pha1set, 2, 1, 1, 1)
        self.lineEdit_pha1act = QtGui.QLineEdit(self.layoutWidget6)
        self.lineEdit_pha1act.setStyleSheet(_fromUtf8("background-color: rgb(217, 217, 217);"))
        self.lineEdit_pha1act.setObjectName(_fromUtf8("lineEdit_pha1act"))
        self.gridLayout.addWidget(self.lineEdit_pha1act, 2, 2, 1, 1)
        self.label_12 = QtGui.QLabel(self.layoutWidget6)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_12.setFont(font)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout.addWidget(self.label_12, 3, 0, 1, 1)
        self.lineEdit_amp2set = QtGui.QLineEdit(self.layoutWidget6)
        self.lineEdit_amp2set.setStyleSheet(_fromUtf8("background-color: rgb(217, 217, 217);"))
        self.lineEdit_amp2set.setObjectName(_fromUtf8("lineEdit_amp2set"))
        self.gridLayout.addWidget(self.lineEdit_amp2set, 3, 1, 1, 1)
        self.lineEdit_amp2act = QtGui.QLineEdit(self.layoutWidget6)
        self.lineEdit_amp2act.setStyleSheet(_fromUtf8("background-color: rgb(217, 217, 217);"))
        self.lineEdit_amp2act.setObjectName(_fromUtf8("lineEdit_amp2act"))
        self.gridLayout.addWidget(self.lineEdit_amp2act, 3, 2, 1, 1)
        self.label_11 = QtGui.QLabel(self.layoutWidget6)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_11.setFont(font)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout.addWidget(self.label_11, 4, 0, 1, 1)
        self.lineEdit_pha2set = QtGui.QLineEdit(self.layoutWidget6)
        self.lineEdit_pha2set.setStyleSheet(_fromUtf8("background-color: rgb(217, 217, 217);"))
        self.lineEdit_pha2set.setObjectName(_fromUtf8("lineEdit_pha2set"))
        self.gridLayout.addWidget(self.lineEdit_pha2set, 4, 1, 1, 1)
        self.lineEdit_pha2act = QtGui.QLineEdit(self.layoutWidget6)
        self.lineEdit_pha2act.setStyleSheet(_fromUtf8("background-color: rgb(217, 217, 217);"))
        self.lineEdit_pha2act.setObjectName(_fromUtf8("lineEdit_pha2act"))
        self.gridLayout.addWidget(self.lineEdit_pha2act, 4, 2, 1, 1)
        self.label_14 = QtGui.QLabel(self.layoutWidget6)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_14.setFont(font)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout.addWidget(self.label_14, 5, 0, 1, 1)
        self.lineEdit_refl_pwlimitset = QtGui.QLineEdit(self.layoutWidget6)
        self.lineEdit_refl_pwlimitset.setObjectName(_fromUtf8("lineEdit_refl_pwlimitset"))
        self.gridLayout.addWidget(self.lineEdit_refl_pwlimitset, 5, 1, 1, 1)
        self.lineEdit_refl_pwlimitact = QtGui.QLineEdit(self.layoutWidget6)
        self.lineEdit_refl_pwlimitact.setStyleSheet(_fromUtf8("background-color: rgb(217, 217, 217);"))
        self.lineEdit_refl_pwlimitact.setObjectName(_fromUtf8("lineEdit_refl_pwlimitact"))
        self.gridLayout.addWidget(self.lineEdit_refl_pwlimitact, 5, 2, 1, 1)
        self.layoutWidget7 = QtGui.QWidget(self.groupBox)
        self.layoutWidget7.setGeometry(QtCore.QRect(20, 24, 241, 98))
        self.layoutWidget7.setObjectName(_fromUtf8("layoutWidget7"))
        self.gridLayout_2 = QtGui.QGridLayout(self.layoutWidget7)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.start = QtGui.QPushButton(self.layoutWidget7)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.start.setFont(font)
        self.start.setObjectName(_fromUtf8("start"))
        self.gridLayout_2.addWidget(self.start, 0, 0, 1, 1)
        self.label_start = QtGui.QLabel(self.layoutWidget7)
        self.label_start.setEnabled(True)
        self.label_start.setStyleSheet(_fromUtf8("background-color: rgb(181, 181, 181);\n"
"min-width:     16px;\n"
"min-height:    16px;    \n"
"max-width:     16px;    \n"
"max-height:    16px;    \n"
"border-radius: 8px;    "))
        self.label_start.setText(_fromUtf8(""))
        self.label_start.setObjectName(_fromUtf8("label_start"))
        self.gridLayout_2.addWidget(self.label_start, 0, 1, 1, 1)
        self.enable = QtGui.QPushButton(self.layoutWidget7)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.enable.setFont(font)
        self.enable.setObjectName(_fromUtf8("enable"))
        self.gridLayout_2.addWidget(self.enable, 0, 2, 1, 1)
        self.label_enable = QtGui.QLabel(self.layoutWidget7)
        self.label_enable.setEnabled(True)
        self.label_enable.setStyleSheet(_fromUtf8("background-color: rgb(181, 181, 181);\n"
"min-width:     16px;\n"
"min-height:    16px;    \n"
"max-width:     16px;    \n"
"max-height:    16px;    \n"
"border-radius: 8px;    "))
        self.label_enable.setText(_fromUtf8(""))
        self.label_enable.setObjectName(_fromUtf8("label_enable"))
        self.gridLayout_2.addWidget(self.label_enable, 0, 3, 1, 1)
        self.start_2 = QtGui.QPushButton(self.layoutWidget7)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.start_2.setFont(font)
        self.start_2.setObjectName(_fromUtf8("start_2"))
        self.gridLayout_2.addWidget(self.start_2, 1, 0, 1, 1)
        self.label_oddeven = QtGui.QLabel(self.layoutWidget7)
        self.label_oddeven.setEnabled(True)
        self.label_oddeven.setStyleSheet(_fromUtf8("background-color: rgb(181, 181, 181);\n"
"min-width:     16px;\n"
"min-height:    16px;    \n"
"max-width:     16px;    \n"
"max-height:    16px;    \n"
"border-radius: 8px;    "))
        self.label_oddeven.setText(_fromUtf8(""))
        self.label_oddeven.setObjectName(_fromUtf8("label_oddeven"))
        self.gridLayout_2.addWidget(self.label_oddeven, 1, 1, 1, 1)
        self.enable_feed = QtGui.QPushButton(self.layoutWidget7)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.enable_feed.setFont(font)
        self.enable_feed.setObjectName(_fromUtf8("enable_feed"))
        self.gridLayout_2.addWidget(self.enable_feed, 1, 2, 1, 1)
        self.label_feed = QtGui.QLabel(self.layoutWidget7)
        self.label_feed.setEnabled(True)
        self.label_feed.setStyleSheet(_fromUtf8("background-color: rgb(181, 181, 181);\n"
"min-width:     16px;\n"
"min-height:    16px;    \n"
"max-width:     16px;    \n"
"max-height:    16px;    \n"
"border-radius: 8px;    "))
        self.label_feed.setText(_fromUtf8(""))
        self.label_feed.setObjectName(_fromUtf8("label_feed"))
        self.gridLayout_2.addWidget(self.label_feed, 1, 3, 1, 1)
        self.Detail = QtGui.QPushButton(self.layoutWidget7)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Detail.setFont(font)
        self.Detail.setObjectName(_fromUtf8("Detail"))
        self.gridLayout_2.addWidget(self.Detail, 2, 0, 1, 1)
        self.Detail_2 = QtGui.QPushButton(self.layoutWidget7)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Detail_2.setFont(font)
        self.Detail_2.setObjectName(_fromUtf8("Detail_2"))
        self.gridLayout_2.addWidget(self.Detail_2, 2, 2, 1, 1)
        self.label_44 = QtGui.QLabel(self.centralwidget)
        self.label_44.setGeometry(QtCore.QRect(210, 40, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_44.setFont(font)
        self.label_44.setObjectName(_fromUtf8("label_44"))
        self.label_45 = QtGui.QLabel(self.centralwidget)
        self.label_45.setGeometry(QtCore.QRect(260, 40, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_45.setFont(font)
        self.label_45.setObjectName(_fromUtf8("label_45"))
        self.groupBox_9 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_9.setGeometry(QtCore.QRect(98, 437, 141, 121))
        self.groupBox_9.setStyleSheet(_fromUtf8("background-color: rgb(235, 235, 235);"))
        self.groupBox_9.setObjectName(_fromUtf8("groupBox_9"))
        self.layoutWidget8 = QtGui.QWidget(self.groupBox_9)
        self.layoutWidget8.setGeometry(QtCore.QRect(9, 19, 121, 94))
        self.layoutWidget8.setObjectName(_fromUtf8("layoutWidget8"))
        self.gridLayout_3 = QtGui.QGridLayout(self.layoutWidget8)
        self.gridLayout_3.setMargin(0)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_15 = QtGui.QLabel(self.layoutWidget8)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_15.setFont(font)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_3.addWidget(self.label_15, 0, 0, 1, 1)
        self.chart1 = QtGui.QPushButton(self.layoutWidget8)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.chart1.setFont(font)
        self.chart1.setObjectName(_fromUtf8("chart1"))
        self.gridLayout_3.addWidget(self.chart1, 0, 1, 1, 1)
        self.label_16 = QtGui.QLabel(self.layoutWidget8)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_16.setFont(font)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_3.addWidget(self.label_16, 1, 0, 1, 1)
        self.lineEdit_ref_pw = QtGui.QLineEdit(self.layoutWidget8)
        self.lineEdit_ref_pw.setStyleSheet(_fromUtf8("background-color: rgb(217, 217, 217);"))
        self.lineEdit_ref_pw.setObjectName(_fromUtf8("lineEdit_ref_pw"))
        self.gridLayout_3.addWidget(self.lineEdit_ref_pw, 1, 1, 1, 1)
        self.label_18 = QtGui.QLabel(self.layoutWidget8)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_18.setFont(font)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout_3.addWidget(self.label_18, 1, 2, 1, 1)
        self.label_17 = QtGui.QLabel(self.layoutWidget8)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_17.setFont(font)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout_3.addWidget(self.label_17, 2, 0, 1, 1)
        self.lineEdit_ref_pha = QtGui.QLineEdit(self.layoutWidget8)
        self.lineEdit_ref_pha.setStyleSheet(_fromUtf8("background-color: rgb(217, 217, 217);"))
        self.lineEdit_ref_pha.setObjectName(_fromUtf8("lineEdit_ref_pha"))
        self.gridLayout_3.addWidget(self.lineEdit_ref_pha, 2, 1, 1, 1)
        self.label_19 = QtGui.QLabel(self.layoutWidget8)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_19.setFont(font)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.gridLayout_3.addWidget(self.label_19, 2, 2, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1335, 24))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.chart1_2, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.popWindow3)
        QtCore.QObject.connect(self.chart1_3, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.popWindow3)
        QtCore.QObject.connect(self.chart1_6, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.popWindow3)
        QtCore.QObject.connect(self.chart1_4, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.popWindow4)
        QtCore.QObject.connect(self.chart1_14, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.popWindow4)
        QtCore.QObject.connect(self.chart1_12, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.popWindow3)
        QtCore.QObject.connect(self.chart1_13, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.popWindow3)
        QtCore.QObject.connect(self.chart1_9, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.popWindow3)
        QtCore.QObject.connect(self.chart1_8, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.popWindow3)
        QtCore.QObject.connect(self.chart1_11, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.popWindow3)
        QtCore.QObject.connect(self.chart1_10, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.popWindow3)
        QtCore.QObject.connect(self.lineEdit_amp1set, QtCore.SIGNAL(_fromUtf8("returnPressed()")), MainWindow.get_Amp1)
        QtCore.QObject.connect(self.Detail, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.popWindow2)
        QtCore.QObject.connect(self.lineEdit_refl_pwlimitset, QtCore.SIGNAL(_fromUtf8("returnPressed()")), MainWindow.get_Refl_pwlimit)
        QtCore.QObject.connect(self.lineEdit_pha1set, QtCore.SIGNAL(_fromUtf8("returnPressed()")), MainWindow.get_Pha1)
        QtCore.QObject.connect(self.lineEdit_amp2set, QtCore.SIGNAL(_fromUtf8("returnPressed()")), MainWindow.get_Amp2)
        QtCore.QObject.connect(self.lineEdit_pha2set, QtCore.SIGNAL(_fromUtf8("returnPressed()")), MainWindow.get_Pha2)
        QtCore.QObject.connect(self.start, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.llrf_start)
        QtCore.QObject.connect(self.chart1, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.popWindow3)
        QtCore.QObject.connect(self.chart1_5, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.popWindow3)
        QtCore.QObject.connect(self.Detail_2, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.popWindow2v2)
        QtCore.QObject.connect(self.enable, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.trigger_start)
        QtCore.QObject.connect(self.start_2, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.Oddeven)
        QtCore.QObject.connect(self.enable_feed, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.Feed_forward)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "DCLS用户工程样机一级界面", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("MainWindow", "VM output", None, QtGui.QApplication.UnicodeUTF8))
        self.label_34.setText(QtGui.QApplication.translate("MainWindow", "VM1", None, QtGui.QApplication.UnicodeUTF8))
        self.chart1_2.setText(QtGui.QApplication.translate("MainWindow", "chart", None, QtGui.QApplication.UnicodeUTF8))
        self.label_53.setText(QtGui.QApplication.translate("MainWindow", "VM2", None, QtGui.QApplication.UnicodeUTF8))
        self.chart1_5.setText(QtGui.QApplication.translate("MainWindow", "chart", None, QtGui.QApplication.UnicodeUTF8))
        self.label_36.setText(QtGui.QApplication.translate("MainWindow", "Power1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_35.setText(QtGui.QApplication.translate("MainWindow", "MW", None, QtGui.QApplication.UnicodeUTF8))
        self.label_56.setText(QtGui.QApplication.translate("MainWindow", "Power2", None, QtGui.QApplication.UnicodeUTF8))
        self.label_54.setText(QtGui.QApplication.translate("MainWindow", "MW", None, QtGui.QApplication.UnicodeUTF8))
        self.label_38.setText(QtGui.QApplication.translate("MainWindow", "Phase1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_37.setText(QtGui.QApplication.translate("MainWindow", "Deg", None, QtGui.QApplication.UnicodeUTF8))
        self.label_52.setText(QtGui.QApplication.translate("MainWindow", "Phase2", None, QtGui.QApplication.UnicodeUTF8))
        self.label_55.setText(QtGui.QApplication.translate("MainWindow", "Deg", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("MainWindow", "SSA output", None, QtGui.QApplication.UnicodeUTF8))
        self.label_40.setText(QtGui.QApplication.translate("MainWindow", "Fwd1", None, QtGui.QApplication.UnicodeUTF8))
        self.chart1_3.setText(QtGui.QApplication.translate("MainWindow", "chart", None, QtGui.QApplication.UnicodeUTF8))
        self.label_59.setText(QtGui.QApplication.translate("MainWindow", "Fwd2", None, QtGui.QApplication.UnicodeUTF8))
        self.chart1_6.setText(QtGui.QApplication.translate("MainWindow", "chart", None, QtGui.QApplication.UnicodeUTF8))
        self.label_43.setText(QtGui.QApplication.translate("MainWindow", "Power1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_39.setText(QtGui.QApplication.translate("MainWindow", "MW", None, QtGui.QApplication.UnicodeUTF8))
        self.label_58.setText(QtGui.QApplication.translate("MainWindow", "Power2", None, QtGui.QApplication.UnicodeUTF8))
        self.label_61.setText(QtGui.QApplication.translate("MainWindow", "MW", None, QtGui.QApplication.UnicodeUTF8))
        self.label_41.setText(QtGui.QApplication.translate("MainWindow", "Phase1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_42.setText(QtGui.QApplication.translate("MainWindow", "Deg", None, QtGui.QApplication.UnicodeUTF8))
        self.label_57.setText(QtGui.QApplication.translate("MainWindow", "Phase2", None, QtGui.QApplication.UnicodeUTF8))
        self.label_60.setText(QtGui.QApplication.translate("MainWindow", "Deg", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_7.setTitle(QtGui.QApplication.translate("MainWindow", "Load", None, QtGui.QApplication.UnicodeUTF8))
        self.label_75.setText(QtGui.QApplication.translate("MainWindow", "Fwd1", None, QtGui.QApplication.UnicodeUTF8))
        self.chart1_11.setText(QtGui.QApplication.translate("MainWindow", "chart", None, QtGui.QApplication.UnicodeUTF8))
        self.label_79.setText(QtGui.QApplication.translate("MainWindow", "Fwd2", None, QtGui.QApplication.UnicodeUTF8))
        self.chart1_10.setText(QtGui.QApplication.translate("MainWindow", "chart", None, QtGui.QApplication.UnicodeUTF8))
        self.label_83.setText(QtGui.QApplication.translate("MainWindow", "Power1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_74.setText(QtGui.QApplication.translate("MainWindow", "MW", None, QtGui.QApplication.UnicodeUTF8))
        self.label_78.setText(QtGui.QApplication.translate("MainWindow", "Power2", None, QtGui.QApplication.UnicodeUTF8))
        self.label_81.setText(QtGui.QApplication.translate("MainWindow", "MW", None, QtGui.QApplication.UnicodeUTF8))
        self.label_77.setText(QtGui.QApplication.translate("MainWindow", "Phase1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_82.setText(QtGui.QApplication.translate("MainWindow", "Deg", None, QtGui.QApplication.UnicodeUTF8))
        self.label_76.setText(QtGui.QApplication.translate("MainWindow", "Phase2", None, QtGui.QApplication.UnicodeUTF8))
        self.label_80.setText(QtGui.QApplication.translate("MainWindow", "Deg", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_8.setTitle(QtGui.QApplication.translate("MainWindow", "KLY output", None, QtGui.QApplication.UnicodeUTF8))
        self.label_85.setText(QtGui.QApplication.translate("MainWindow", "Fwd1", None, QtGui.QApplication.UnicodeUTF8))
        self.chart1_13.setText(QtGui.QApplication.translate("MainWindow", "chart", None, QtGui.QApplication.UnicodeUTF8))
        self.label_89.setText(QtGui.QApplication.translate("MainWindow", "Fwd2", None, QtGui.QApplication.UnicodeUTF8))
        self.chart1_12.setText(QtGui.QApplication.translate("MainWindow", "chart", None, QtGui.QApplication.UnicodeUTF8))
        self.label_93.setText(QtGui.QApplication.translate("MainWindow", "Power1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_84.setText(QtGui.QApplication.translate("MainWindow", "MW", None, QtGui.QApplication.UnicodeUTF8))
        self.label_88.setText(QtGui.QApplication.translate("MainWindow", "Power2", None, QtGui.QApplication.UnicodeUTF8))
        self.label_91.setText(QtGui.QApplication.translate("MainWindow", "MW", None, QtGui.QApplication.UnicodeUTF8))
        self.label_87.setText(QtGui.QApplication.translate("MainWindow", "Phase1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_92.setText(QtGui.QApplication.translate("MainWindow", "Deg", None, QtGui.QApplication.UnicodeUTF8))
        self.label_86.setText(QtGui.QApplication.translate("MainWindow", "Phase2", None, QtGui.QApplication.UnicodeUTF8))
        self.label_90.setText(QtGui.QApplication.translate("MainWindow", "Deg", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_6.setTitle(QtGui.QApplication.translate("MainWindow", "Defl. input", None, QtGui.QApplication.UnicodeUTF8))
        self.label_67.setText(QtGui.QApplication.translate("MainWindow", "Phase2", None, QtGui.QApplication.UnicodeUTF8))
        self.label_73.setText(QtGui.QApplication.translate("MainWindow", "Power1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_50.setText(QtGui.QApplication.translate("MainWindow", "Fwd1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_69.setText(QtGui.QApplication.translate("MainWindow", "Fwd2", None, QtGui.QApplication.UnicodeUTF8))
        self.label_70.setText(QtGui.QApplication.translate("MainWindow", "Deg", None, QtGui.QApplication.UnicodeUTF8))
        self.label_68.setText(QtGui.QApplication.translate("MainWindow", "Power2", None, QtGui.QApplication.UnicodeUTF8))
        self.label_49.setText(QtGui.QApplication.translate("MainWindow", "MW", None, QtGui.QApplication.UnicodeUTF8))
        self.label_71.setText(QtGui.QApplication.translate("MainWindow", "MW", None, QtGui.QApplication.UnicodeUTF8))
        self.chart1_9.setText(QtGui.QApplication.translate("MainWindow", "chart", None, QtGui.QApplication.UnicodeUTF8))
        self.label_72.setText(QtGui.QApplication.translate("MainWindow", "Deg", None, QtGui.QApplication.UnicodeUTF8))
        self.chart1_8.setText(QtGui.QApplication.translate("MainWindow", "chart", None, QtGui.QApplication.UnicodeUTF8))
        self.label_51.setText(QtGui.QApplication.translate("MainWindow", "Phase1", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_5.setTitle(QtGui.QApplication.translate("MainWindow", "Mod and KLY Refl.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_62.setText(QtGui.QApplication.translate("MainWindow", "K5 Refl", None, QtGui.QApplication.UnicodeUTF8))
        self.chart1_4.setText(QtGui.QApplication.translate("MainWindow", "chart", None, QtGui.QApplication.UnicodeUTF8))
        self.label_47.setText(QtGui.QApplication.translate("MainWindow", "MW", None, QtGui.QApplication.UnicodeUTF8))
        self.label_46.setText(QtGui.QApplication.translate("MainWindow", "Mod.5 HV", None, QtGui.QApplication.UnicodeUTF8))
        self.chart1_14.setText(QtGui.QApplication.translate("MainWindow", "chart", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Klystron5", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("MainWindow", "       Set", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("MainWindow", "     Actuall", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "AmpO(%)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("MainWindow", "PhaseO(°)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("MainWindow", "AmpE(%)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("MainWindow", "PhaseE(°)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("MainWindow", "Refl.PW Limit", None, QtGui.QApplication.UnicodeUTF8))
        self.start.setText(QtGui.QApplication.translate("MainWindow", "Start", None, QtGui.QApplication.UnicodeUTF8))
        self.enable.setText(QtGui.QApplication.translate("MainWindow", "Trigger Enable", None, QtGui.QApplication.UnicodeUTF8))
        self.start_2.setText(QtGui.QApplication.translate("MainWindow", "Odd Even", None, QtGui.QApplication.UnicodeUTF8))
        self.enable_feed.setText(QtGui.QApplication.translate("MainWindow", " Feed forward", None, QtGui.QApplication.UnicodeUTF8))
        self.Detail.setText(QtGui.QApplication.translate("MainWindow", "Details", None, QtGui.QApplication.UnicodeUTF8))
        self.Detail_2.setText(QtGui.QApplication.translate("MainWindow", "Details2", None, QtGui.QApplication.UnicodeUTF8))
        self.label_44.setText(QtGui.QApplication.translate("MainWindow", "1:Odd", None, QtGui.QApplication.UnicodeUTF8))
        self.label_45.setText(QtGui.QApplication.translate("MainWindow", "2:Even", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_9.setTitle(QtGui.QApplication.translate("MainWindow", "Ref output", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("MainWindow", "RFref", None, QtGui.QApplication.UnicodeUTF8))
        self.chart1.setText(QtGui.QApplication.translate("MainWindow", "chart", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("MainWindow", "Power", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("MainWindow", "MW", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("MainWindow", "Phase", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("MainWindow", "Deg", None, QtGui.QApplication.UnicodeUTF8))

import pictures_rc
